export interface Country {
  code: string;
  nameES: string;
  nameENG: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', nameES: 'Afganistán', nameENG: 'Afghanistan' },
  { code: 'AL', nameES: 'Albania', nameENG: 'Albania' },
  { code: 'DE', nameES: 'Alemania', nameENG: 'Germany' },
  { code: 'AD', nameES: 'Andorra', nameENG: 'Andorra' },
  { code: 'AO', nameES: 'Angola', nameENG: 'Angola' },
  { code: 'AR', nameES: 'Argentina', nameENG: 'Argentina' },
  { code: 'AM', nameES: 'Armenia', nameENG: 'Armenia' },
  { code: 'AU', nameES: 'Australia', nameENG: 'Australia' },
  { code: 'AT', nameES: 'Austria', nameENG: 'Austria' },
  { code: 'AZ', nameES: 'Azerbaiyán', nameENG: 'Azerbaijan' },
  { code: 'BE', nameES: 'Bélgica', nameENG: 'Belgium' },
  { code: 'BO', nameES: 'Bolivia', nameENG: 'Bolivia' },
  { code: 'BR', nameES: 'Brasil', nameENG: 'Brazil' },
  { code: 'BG', nameES: 'Bulgaria', nameENG: 'Bulgaria' },
  { code: 'CA', nameES: 'Canadá', nameENG: 'Canada' },
  { code: 'CL', nameES: 'Chile', nameENG: 'Chile' },
  { code: 'CN', nameES: 'China', nameENG: 'China' },
  { code: 'CO', nameES: 'Colombia', nameENG: 'Colombia' },
  { code: 'KR', nameES: 'Corea del Sur', nameENG: 'South Korea' },
  { code: 'KP', nameES: 'Corea del Norte', nameENG: 'North Korea' },
  { code: 'CR', nameES: 'Costa Rica', nameENG: 'Costa Rica' },
  { code: 'CU', nameES: 'Cuba', nameENG: 'Cuba' },
  { code: 'DK', nameES: 'Dinamarca', nameENG: 'Denmark' },
  { code: 'EC', nameES: 'Ecuador', nameENG: 'Ecuador' },
  { code: 'EG', nameES: 'Egipto', nameENG: 'Egypt' },
  { code: 'SV', nameES: 'El Salvador', nameENG: 'El Salvador' },
  { code: 'ES', nameES: 'España', nameENG: 'Spain' },
  { code: 'US', nameES: 'Estados Unidos', nameENG: 'United States' },
  { code: 'EE', nameES: 'Estonia', nameENG: 'Estonia' },
  { code: 'ET', nameES: 'Etiopía', nameENG: 'Ethiopia' },
  { code: 'PH', nameES: 'Filipinas', nameENG: 'Philippines' },
  { code: 'FI', nameES: 'Finlandia', nameENG: 'Finland' },
  { code: 'FR', nameES: 'Francia', nameENG: 'France' },
  { code: 'GR', nameES: 'Grecia', nameENG: 'Greece' },
  { code: 'GT', nameES: 'Guatemala', nameENG: 'Guatemala' },
  { code: 'HN', nameES: 'Honduras', nameENG: 'Honduras' },
  { code: 'HU', nameES: 'Hungría', nameENG: 'Hungary' },
  { code: 'IN', nameES: 'India', nameENG: 'India' },
  { code: 'ID', nameES: 'Indonesia', nameENG: 'Indonesia' },
  { code: 'IR', nameES: 'Irán', nameENG: 'Iran' },
  { code: 'IQ', nameES: 'Irak', nameENG: 'Iraq' },
  { code: 'IE', nameES: 'Irlanda', nameENG: 'Ireland' },
  { code: 'IS', nameES: 'Islandia', nameENG: 'Iceland' },
  { code: 'IL', nameES: 'Israel', nameENG: 'Israel' },
  { code: 'IT', nameES: 'Italia', nameENG: 'Italy' },
  { code: 'JP', nameES: 'Japón', nameENG: 'Japan' },
  { code: 'MX', nameES: 'México', nameENG: 'Mexico' },
  { code: 'NL', nameES: 'Países Bajos', nameENG: 'Netherlands' },
  { code: 'PE', nameES: 'Perú', nameENG: 'Peru' },
  { code: 'PL', nameES: 'Polonia', nameENG: 'Poland' },
  { code: 'PT', nameES: 'Portugal', nameENG: 'Portugal' },
  { code: 'GB', nameES: 'Reino Unido', nameENG: 'United Kingdom' },
  { code: 'CZ', nameES: 'República Checa', nameENG: 'Czech Republic' },
  { code: 'DO', nameES: 'República Dominicana', nameENG: 'Dominican Republic' },
  { code: 'RO', nameES: 'Rumanía', nameENG: 'Romania' },
  { code: 'RU', nameES: 'Rusia', nameENG: 'Russia' },
  { code: 'ZA', nameES: 'Sudáfrica', nameENG: 'South Africa' },
  { code: 'SE', nameES: 'Suecia', nameENG: 'Sweden' },
  { code: 'CH', nameES: 'Suiza', nameENG: 'Switzerland' },
  { code: 'TH', nameES: 'Tailandia', nameENG: 'Thailand' },
  { code: 'TR', nameES: 'Turquía', nameENG: 'Turkey' },
  { code: 'UA', nameES: 'Ucrania', nameENG: 'Ukraine' },
  { code: 'UY', nameES: 'Uruguay', nameENG: 'Uruguay' },
  { code: 'VE', nameES: 'Venezuela', nameENG: 'Venezuela' },
  { code: 'VN', nameES: 'Vietnam', nameENG: 'Vietnam' },
  { code: 'ZW', nameES: 'Zimbabue', nameENG: 'Zimbabwe' }
];
